### ISSUE TITLE
feature request - websocket API

### ISSUE THREAD

**Issue by ddefigueiredo** [neufeldtech/secretmessage-go#14]
The current version of this app exposes an HTTP point to the internet so that slack can reach it. This increases the attack surface for the app. Slack also provides a [websocket interface](https://api.slack.com/apis/connections/socket) that allows for the app to be placed behind a firewall (and out of direct reach of attackers). 

Is there any interest in changing the app to also support communication over websockets?

**Comment by neufeldtech** [comment]
Hey @ddefigueiredo,

While this is open source, I haven't specifically taken into consideration specific support for self-hosting options, including how oauth (app installation) would work for cases that are not the primary instances that I run + support. 

Feel free to fork the repo and experiment with a websocket implementation, but I don't have time to commit to making (or integrating) changes like this at this time.

**Comment by ddefigueiredo** [comment]
Is the application being maintained elsewhere? I don't see a lot of activity (last commit 2 months ago) and it appears there are a few dependencies that need to be updated.
